name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install dependencies
      run: sudo apt-get install -y gcc

    - name: Build
      run: gcc -o hdlc_test hdlc.c main.c

    - name: Run tests
      run: ./hdlc_test
